### ISSUE TITLE
fit Manipulations::FIT_FILL not working as expected

### ISSUE THREAD

**Issue by dryror** [spatie/image#33]
_Edit:_ 
Looks like this is intended by Glide:
> `fill:` Resizes the image to fit within the width and height boundaries **without cropping or distorting the image**, and the remaining space is filled with the background color. The resulting image will match the constraining dimensions. 

I'm assuming the result is due to the "without distorting the image" part.

Perhaps it's worth updating your documentation to match? (or just link through to the glide documentation).
_End edit_

First, thank you very much for your packages. They really help!

I'm using the medialibrary package in a laravel 5.4 project, but figured the issue belonged here since its a manipulation problem.

I'm having some problems with the fit `Manipulations::FIT_FILL` when the original image is smaller then the fit dimensions (enlarging the image). 

It appears that it is acting more like `FIT_MAX` then `FIT_CONTAIN` in that the image doesn't size above it's original dimensions.

Original image: 
https://via.placeholder.com/400x400

Conversion: 

```php
$this->addMediaConversion('gallery')
        ->fit(Manipulations::FIT_FILL, 1000, 964)
        ->background('ffffff');
```

Resulting image: 
https://s3-ap-southeast-2.amazonaws.com/cubro-dev/41f795fdf1ef9647d7465538dfa48c64/conversions/gallery.jpg

Based on the documentation, I was expecting the resulting base image to be resized to 964x964 with an 18px white fill on either side. Instead, the image remains at 400x400 with the remained filled.

**Comment by freekmurze** [comment]
> Perhaps it's worth updating your documentation to match?

Feel free to send a PR to our docs.

**Comment by o15a3d4l11s2** [comment]
I think that this issue is still relevant. Based on Glide's documentation:
> `max`: Resizes the image to fit within the width and height boundaries without cropping, distorting or altering the aspect ratio, and will also not increase the size of the image if it is smaller than the output size.

>`fill`: Resizes the image to fit within the width and height boundaries without cropping or distorting the image, and the remaining space is filled with the background color. The resulting image will match the constraining dimensions.

So `max` explicitly states that it will not increase the image size. But this is not the same for `fill`. So a person would expect that if they resize an image of dimension 300x300 to fit a container of 500x600, then the output image would be 500x600 and it will contain the actual picture as 500x500 and 50 from top and bottom would be transparent (or the specified background colour).

At the moment the only possible way to make it happen is to double-fit the image like this:
```php
$this->addMediaConversion('example')->fit(Manipulations::FIT_CONTAIN, width: 500, height: 600)->apply()->fit(Manipulations::FIT_FILL, width: 500, height: 600)->background('white');
```

With the current implementation "fill" actually does not fill, it is actually a `max` with a background.
