### ISSUE TITLE
Make temporary path configurable

### ISSUE THREAD

**Issue by mathiassname** [spatie/image#41]
I use the Laravel 5.4 on an hosting package with your medialibrary package. I ran in the case that the /tmp path is not writable/readable. In many cases you can prevent it by change php.ini settings.

Is it possible to make the path configurable and set sys_get_temp_dir() as default?

https://github.com/spatie/image/blob/d868b79d451046877c225af92a40114734eb4e5a/src/GlideConversion.php#L50

**Comment by freekmurze** [comment]
In the config file there's a key to specify the path of the temp dir to be used.

**Comment by flexelektro** [comment]
This is still an issue.
The temp dir in the config file is not used in the GlideConversion.php, and automatically falls back to /tmp which is not readable.
sys_get_temp_dir often makes problems / is not readable on shared servers.

Really my only solution here is to hard code 
`
   $this->conversionResult = config('medialibrary.temporary_directory_path')
`
on line 50 in GlideConversion.php and 

`
$config = [
            'source' => dirname($inputFile),
            'cache' =>  config("medialibrary.temporary_directory_path"),
            'driver' => $this->imageDriver,
        ];
`
on line 80, so that the temp dir in from the config file is used.
