### ISSUE TITLE
JPG quality loss even when quality set to 100

### ISSUE THREAD

**Issue by justinmoh** [spatie/image#71]
I new up a laravel project to test it out, and find that the image was greatly compressed when I just go through any manipulation.

```php
$path = 'storage/test-image.JPG';
$savePath = 'storage/test-image-saved.JPG';

$image = \Spatie\Image\Image::load(public_path($path));

$image
    ->height($image->getHeight()) // manipulating height to its original height
    ->save(public_path($savePath));

$originalSize = File::size(public_path($path));  // 1.7MB
$savedSize = File::size(public_path($savePath));  // 207KB
```

Then I added `->quality(100)`, but the image is still compressed, and experiencing the same colour loss.

```php
$image
    ->quality(100)
    ->height($image->getHeight())
    ->save(public_path($savePath));

$originalSize = File::size(public_path($path));  // 1.7MB
$savedSize = File::size(public_path($savePath));  // 596KB
```

This is the first time I really look into the detail of image manipulation, the outcome is unexpected. I tried with some images with PNG extension, and didn't find similar issue.

Are there any fundamental mistakes I probably made?

This is the image I used: https://yunism.sgp1.cdn.digitaloceanspaces.com/local/media/10807/10047-5.JPG

**Comment by matthew-inamdar** [comment]
Hey @justinmoh 👋

I **think** this may be due to how JEPG works. JPEG is naturally a lossy format, so even with quality set to 100% it will still compress slightly.

PNG is lossless on the other hand, which explains why you didn't notice any compression.

Look at this answer on SO for more info: https://stackoverflow.com/a/48578831/5745438
